### ISSUE TITLE
This is my crush

### ISSUE THREAD

**Issue by ghost** [EvilEagleTwitch/Schlechter-Discord#1]
https://www.youtube.com/watch?v=kef6ZkdgPM0&t=901s

**Comment by EvilEagleTwitch** [comment]
mine too

**Comment by ghost** [comment]
I met him at https://kellertreff.com/

**Comment by ghost** [comment]
This is my favorite site gopher://taz.de:70/1/!5474725

**Comment by ghost** [comment]
The fish doesn't wanna sex me :((((((
